name: Deploy to server

on:
  push:
    branches: [main]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  deploy-prod:
    name: Deploy main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd /var/www/tecweb/tecweb/
            ls -al
            git pull